# -*- coding: utf-8 -*-
"""DSF_Project_Progress.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EZL6cGeLXgOenRsAnZxvLr2abR2psNpF
"""

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

import os

directory = os.path.join("c:\\","C:\Fall2019\DSF\Project\Florida\Voter_Registration_20190910\20190910_VoterDetail")
for root,dirs,files in os.walk(directory):
    for file in files:
       if file.endswith(".txt"):
           f=open(file, 'r')
            
           f.close()